package org.example.day13.예외처리;

public class 예외처리Main {
    public static void main(String[] args) throws Exception  {
        에러발생2 error = new 에러발생2();
        error.call();
        System.out.println("에러발생 후 실행될까요..!!!!!");
        System.out.println("에러발생 후 실행될까요..!!!!!");
        System.out.println("에러발생 후 실행될까요..!!!!!");
        System.out.println("에러발생 후 실행될까요..!!!!!");

    }
}
